apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sraza-ana/local-argo-test
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: fastapi-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true